### ISSUE TITLE
`BadResponseError(response)` if flex query result is csv

### ISSUE THREAD

**Issue by pavitrakumar78** [csingley/ibflex#29]
Hi,

I'm getting a bad response error if my flex query's output is a csv file.

example of stack trace: 

```
>>> response = client.download(token, query_id)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/sample_env/env/lib/python3.8/site-packages/ibflex/client.py", line 117, in download
    status = check_statement_response(response)
  File "/root/sample_env/env/lib/python3.8/site-packages/ibflex/client.py", line 224, in check_statement_response
    raise BadResponseError(response)
ibflex.client.BadResponseError: b'"ClientAccountID","AccountAlias","Model","CurrencyPrimary","FXRateToBase","AssetClass","Symbol","Description","Conid","SecurityID","SecurityIDType","CUSIP","ISIN","ListingExchange","UnderlyingConid","UnderlyingSymbol","UnderlyingSecurityID","UnderlyingListingExchange","Issuer","Multiplier","Strike","Expiry","TradeID","Put/Call","ReportDate","PrincipalAdjustFactor","DateTime","TradeDate","SettleDateTarget","TransactionType","Exchange","Quantity","TradePrice","TradeMoney","Proceeds","Taxes","IBCommission","IBCommissionCurrency","NetCash","ClosePrice","Open/CloseIndicator","Notes/Codes","CostBasis","FifoPnlRealized","FxPnl","MtmPnl","OrigTradePrice","OrigTradeDate","OrigTradeID","OrigOrderID","ClearingFirmID","TransactionID","Buy/Sell","IBOrderID","IBExecID","BrokerageOrderID","OrderReference","VolatilityOrderLink","ExchOrderID","ExtExecID","OrderTime","OpenDateTime","HoldingPeriodDateTime","WhenRealized","WhenReopened","LevelOfDetail","ChangeInPrice","ChangeInQuantity","OrderType","TraderID","IsAPIOrder","AccruedInterest"\n"<ACC-ID>","","","USD","1","STK","ALK","ALASKA AIR GROUP INC","4352","US0116591092","ISIN","011659109","US0116591092","NYSE","","","","","","1","","","3608520076","","20210312","","20210312,133059","20210312","20210316","ExchTrade","IBKRATS","0.3088","68.41","21.125008","-21.125008","0","-0.21125008","USD","-21.33625808","68.02","O","FP;P","21.33625808","0","0","-0.1204","0","","","0","","15738557515","BUY","1807825233","000102df.604bd43a.01.01","0030c27b.0000ebaf.604b5ec3.0001","","","N/A","0030c27b.00018c81.609ee3f4.0001","20210312,133059","","","","","EXECUTION","0","0","LMT","","N","0"\n"<ACC-ID>","","","USD","1","STK","ALK","ALASKA AIR GROUP INC","4352","US0116591092","ISIN","011659109","US0116591092","NYSE","","","","","","1","","","3608520082","","20210312","","20210312,133059","20210312","20210316","ExchTrade","IBKRATS","7","68.41","478.87","-478.87","0","-0.78874992","USD","-479.65874992","68.02","O","P","479.65874992","0","0","-2.73","0","","","0","","15738557532","BUY","1807825233","0000d322.604bcd09.01.01","0030c27b.0000ebaf.604b5ec3.0001","","","N/A","378047500B"
...
...
```

The `check_statement_response` checks if 'FlexQueryResponse' is in the result - why is that required? and is it tested for all types of outputs (txt, XML, csv)? 

Edit: maybe it's better to allow a parameter to skip checking in the `client.download(...)` function?

**Comment by pavitrakumar78** [comment]
Realized this library is geared towards XML-type flex queries. I'm closing this issue.

**Comment by csingley** [comment]
A subtle yet important detail, all but buried deep within a dense thicket of technical documentation!
