### ISSUE TITLE
Issues with parsing notes and serialNumber

### ISSUE THREAD

**Issue by pavitrakumar78** [csingley/ibflex#30]
Hi,

I've been experimenting with ibflex and found 2 issues:

Here's the XML file:
[sample.zip](https://github.com/csingley/ibflex/files/6215376/sample.zip)

First, this is how I generated the XML file:
```
token = "..."
query_id = "..."

response = client.download(token, query_id)
with open('sample.xml', 'w') as outfile:
    outfile.write(response.decode('utf-8'))
response_p = parser.parse("sample.xml") #errors here
```
Second, here's the flex query configuration:
![screencapture-interactivebrokers-co-in-AccountManagement-AmAuthentication-2021-03-27-13_47_28](https://user-images.githubusercontent.com/5354407/112715071-31053c80-8f04-11eb-8bd7-7346ca788423.png)
Note that under trades, all boxes are checked.

------------

Issues:

1. When parsing the file, I get the following error: `FlexParserError: Trade.notes - Can't convert 'FP;P' to <class 'tuple'>`

```
response1 = parser.parse("sample.xml")
Traceback (most recent call last):

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 312, in convert
    return Type(prepped_value)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 280, in <genexpr>
    enums.Code(v)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\enum.py", line 339, in __call__
    return cls.__new__(cls, value)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\enum.py", line 662, in __new__
    raise ve_exc

ValueError: 'FP' is not a valid Code


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 159, in parse_element_attr
    converted = ATTRIB_CONVERTERS[Type](value=value)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 314, in convert
    raise FlexParserError(

FlexParserError: Can't convert 'FP;P' to <class 'tuple'>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-29-c6dab1bf5206>", line 1, in <module>
    response1 = parser.parse("sample.xml")

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 53, in parse
    parsed = parse_element(root)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 85, in parse_element
    return parse_data_element(elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 125, in parse_data_element
    contained_elements = {child.tag: parse_element(child) for child in elem}

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 125, in <dictcomp>
    contained_elements = {child.tag: parse_element(child) for child in elem}

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 80, in parse_element
    return parse_element_container(elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 101, in parse_element_container
    instances = tuple(parse_data_element(child) for child in elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 101, in <genexpr>
    instances = tuple(parse_data_element(child) for child in elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 125, in parse_data_element
    contained_elements = {child.tag: parse_element(child) for child in elem}

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 125, in <dictcomp>
    contained_elements = {child.tag: parse_element(child) for child in elem}

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 83, in parse_element
    return parse_element_container(elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 101, in parse_element_container
    instances = tuple(parse_data_element(child) for child in elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 101, in <genexpr>
    instances = tuple(parse_data_element(child) for child in elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 115, in parse_data_element
    attrs = dict(

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 116, in <genexpr>
    parse_element_attr(Class, k, v)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 166, in parse_element_attr
    raise FlexParserError(msg)

FlexParserError: Trade.notes - Can't convert 'FP;P' to <class 'tuple'>
```

I tried fixing it by doing:
```
response = response.decode('utf-8').replace('FP;P','').replace('P;RP','')
```
and it works. But I'm not sure why the error was caused in the first place.

2. After using the workaround above, the next error I run into is: `FlexParserError: Trade has no attribute 'serialNumber'`

```
response = client.download(token, query_id)
response = response.decode('utf-8').replace('FP;P','').replace('P;RP','')
#with open('sample.xml', 'w') as outfile:
#    outfile.write(response.decode('utf-8'))
parsed_response = parser.parse(bytes(response, 'utf-8'))
Traceback (most recent call last):

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 115, in parse_data_element
    attrs = dict(

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 116, in <genexpr>
    parse_element_attr(Class, k, v)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 156, in parse_element_attr
    Type = Class.__annotations__[name]

KeyError: 'serialNumber'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-30-4183a17da92d>", line 5, in <module>
    parsed_response = parser.parse(bytes(response, 'utf-8'))

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 53, in parse
    parsed = parse_element(root)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 85, in parse_element
    return parse_data_element(elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 125, in parse_data_element
    contained_elements = {child.tag: parse_element(child) for child in elem}

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 125, in <dictcomp>
    contained_elements = {child.tag: parse_element(child) for child in elem}

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 80, in parse_element
    return parse_element_container(elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 101, in parse_element_container
    instances = tuple(parse_data_element(child) for child in elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 101, in <genexpr>
    instances = tuple(parse_data_element(child) for child in elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 125, in parse_data_element
    contained_elements = {child.tag: parse_element(child) for child in elem}

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 125, in <dictcomp>
    contained_elements = {child.tag: parse_element(child) for child in elem}

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 83, in parse_element
    return parse_element_container(elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 101, in parse_element_container
    instances = tuple(parse_data_element(child) for child in elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 101, in <genexpr>
    instances = tuple(parse_data_element(child) for child in elem)

  File "F:\Dev\WPy64-3870\python-3.8.7.amd64\lib\site-packages\ibflex\parser.py", line 121, in parse_data_element
    raise FlexParserError(msg)

FlexParserError: Trade has no attribute 'serialNumber'
```

I'm not able to solve this error. I manually check the XML file and did find 'serialNumber` field for all entries, but still, the error occurs. 

---------

Edit 1:
If I uncheck the following fields under "Trade" section, then I'm able to solve the 2nd issue - but why does this happen?
![image](https://user-images.githubusercontent.com/5354407/112715497-7aef2200-8f06-11eb-9259-a71398981abb.png)

**Comment by csingley** [comment]
Did you try looking in `ibflex.Types`  and `ibflex.enums`?  The parser is pretty clearly telling you that you're feeding it data that doesn't match its schema.

What exactly is an "FP" type trade, and since when did trades have serial numbers??

IB doesn't publish a complete specification.  I have no way of knowing all possible data that you will download.  However, I have exerted every effort to make it extremely easy for users to update the schema to match the data they encounter.  If you can submit a PR with the updates, preferably including relevant real-world data in test case in `tests/test_types.py`, that'd be great.  Be the change you wish to see in the world!

**Comment by pavitrakumar78** [comment]
I understand that it's not possible to keep updating with IB's changes with schema.

> What exactly is an "FP" type trade,
Not sure either. The trades I shared all have fractional shares. Maybe it's that?

> and since when did trades have serial numbers??
if you expand the trade section in the flex query creation process, it's at the very bottom. Clicking on "Select all" seems to have selected that and a few other fields that caused problems.

I've submitted a pull request. But I'm not clear about one thing: the difference between "PR;P" and "FP;P" - for now, I've assumed both are fractional shares.

Please take a look at pull requests #31 and #32

**Comment by csingley** [comment]
> I understand that it's not possible to keep updating with IB's changes with schema.

I'm glad you understand - so many changes, and so many financial instruments that I never deal in.  I'm guessing these are Bitcoin trades that are blowing up here, which are treated as commodities, traded in tiny fractions, perhaps with rounding that requires disclosure to the client (i.e. you).

If you generate a PDF statement from the same data, at the bottom of the statement they will include a footnote explaining the meaning of each code used in the trade notes.  It will probably be helpful in understanding "FP" and "RP".
